stationCodes = [
    {'code':'KATL', 'city':'Atlanta', 'state':'Georgia', 'count':0},
    {'code':'KBDL', 'city':'Hartford', 'state':'Connecticut', 'count':0 }, 
    {'code':'KBNA', 'city':'Nashville', 'state':'Tennessee', 'count':0 },
    {'code':'KBOI', 'city':'Boise', 'state':'Idaho', 'count':0 },
    {'code':'KBOS', 'city':'Boston', 'state':'Massachusetts', 'count':0 },
    {'code':'KBUF', 'city':'Buffalo', 'state':'New York', 'count':0 },
    {'code':'KBUR', 'city':'Burbank', 'state':'California', 'count':0 },
    {'code':'KBWI', 'city':'Baltimore', 'state':'Maryland', 'count':0 },
    {'code':'KCMH', 'city':'Columbus', 'state':'Ohio', 'count':0 },
    {'code':'KCQT', 'city':'Los Angeles', 'state':'California', 'count':0 },
    {'code':'KCVG', 'city':'Cincinnati', 'state':'Ohio', 'count':0 }, 
    {'code':'KDCA', 'city':'Washington', 'state':'District of Columbia', 'count':0 },
    {'code':'KDEN', 'city':'Denver', 'state':'Colorado', 'count':0 },
    {'code':'KDFW', 'city':'Dallas', 'state':'Texas', 'count':0 },
    {'code':'KDTW', 'city':'Detroit', 'state':'Michigan', 'count':0 },
    {'code':'KFAT', 'city':'Fresno', 'state':'California', 'count':0 },
    {'code':'KGEG', 'city':'Spokane', 'state':'Washington', 'count':0 },
    {'code':'KIAD', 'city':'Alexandria', 'state':'Virginia', 'count':0 }, 
    {'code':'KIAH', 'city':'Houston', 'state':'Texas', 'count':0 },
    {'code':'KLAS', 'city':'Las Vegas', 'state':'Nevada', 'count':0 },
    {'code':'KLGA', 'city':'New York', 'state':'New York', 'count':0 },
    {'code':'KLIT', 'city':'Little Rock', 'state':'Arkansas', 'count':0 },
    {'code':'KMEM', 'city':'Memphis', 'state':'Tennessee', 'count':0 },
    {'code':'KMSP', 'city':'Minneapolis', 'state':'Minnesota', 'count':0 },
    {'code':'KMSY', 'city':'New Orleans', 'state':'Louisiana', 'count':0 },
    {'code':'KORD', 'city':'Chicago', 'state':'Illinois', 'count':0 },
    {'code':'KPDX', 'city':'Portland', 'state':'Oregon', 'count':0 },
    {'code':'KPHL', 'city':'Philadelphia', 'state':'Pennsylvania', 'count':0 },
    {'code':'KPHX', 'city':'Phoenix', 'state':'Arizona', 'count':0 },
    {'code':'KPIT', 'city':'Pittsburgh', 'state':'Pennsylvania', 'count':0 },
    {'code':'KPWM', 'city':'Manchester', 'state':'New Hampshire', 'count':0 },
    {'code':'KRDU', 'city':'Raleigh', 'state':'North Carolina', 'count':0 },
    {'code':'KRIC', 'city':'Richmond', 'state':'Virginia', 'count':0 },
    {'code':'KSAC', 'city':'Sacramento', 'state':'California', 'count':0 },
    {'code':'KSEA', 'city':'Seattle', 'state':'Washington', 'count':0 },
    {'code':'KSFO', 'city':'San Francisco', 'state':'California', 'count':0 },
    {'code':'KSLC', 'city':'Salt Lake City', 'state':'Utah', 'count':0 },
    {'code':'KSTL', 'city':'St. Louis', 'state':'Missouri', 'count':0 }, 
]